name: MERN CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Backend Install
    - name: Install Backend Dependencies
      run: |
        cd Backend
        npm install
        npm install --legacy-peer-deps

    # Frontend Install
    - name: Install Frontend Dependencies
      run: |
        cd Frontend
        npm install

    # Admin Install
    - name: Install Admin Dependencies
      run: |
        cd Admin
        npm install

    # Frontend Build
    - name: Build Frontend
      run: |
        cd Frontend
        npm run build